# Generated by Django 5.0.3 on 2024-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], default='Bachelor', max_length=16),
        ),
    ]
