# Generated by Django 5.0.3 on 2024-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=128)),
                ('phobe_number', models.CharField(max_length=16)),
                ('sponsorship_sum', models.CharField(max_length=16)),
                ('spent_sum', models.CharField(default=0, max_length=16)),
                ('type', models.CharField(choices=[('Physical_person', 'Phyical Person'), ('Legal_entity', 'Legal Entity')], default='Physical_person', max_length=16)),
                ('status', models.CharField(choices=[('New', 'New'), ('Moderation', 'Mod'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='New', max_length=16)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
