# Generated by Django 5.0.3 on 2024-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Moderation', 'Mod'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='New', max_length=16),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('Physical_person', 'Phyical Person'), ('Legal_entity', 'Legal Entity')], default='Physical_person', max_length=16),
        ),
    ]
