# Generated by Django 5.0.3 on 2024-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsor_status_alter_sponsor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='phobe_number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Moderation', 'Mod'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='New', max_length=16),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('Physical_person', 'Phyical Person'), ('Legal_entity', 'Legal Entity')], default='Physical_person', max_length=16),
        ),
    ]
